services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=two_farm_db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  farm:
    build:
      context: ../..
      dockerfile: examples/farm/Dockerfile
    ports:
      - "3033:3033"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/two_farm_db
      - PORT=3033
      - EQUIP_PORT=4044
      - ENV=development
      - PREFIX=farm
      - PLATFORM_URL=http://farm:3033
    volumes:
      - ./farm:/app/config
    depends_on:
      mongodb:
        condition: service_healthy

  equipment:
    build:
      context: ../..
      dockerfile: examples/farm/Dockerfile
    ports:
      - "4044:4044"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/two_farm_db
      - PORT=4044
      - FARM_PORT=3033
      - ENV=development
      - PREFIX=equipment
      - PLATFORM_URL=http://equipment:4044
    volumes:
      - ./equipment:/app/config
    depends_on:
      mongodb:
        condition: service_healthy
