services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=farm_development
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=farm_development
      - MYSQL_USER=farm
      - MYSQL_PASSWORD=farm123
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=farm_development
      - POSTGRES_USER=farm
      - POSTGRES_PASSWORD=farm123
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U farm -d farm_development" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  farm-service:
    build:
      context: ../..
      dockerfile: examples/farm/Dockerfile
    ports:
      - "3033:3033"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/farm_db
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=farm_development
      - POSTGRES_USER=farm
      - POSTGRES_PASSWORD=farm123
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=farm_development
      - MYSQL_USER=farm
      - MYSQL_PASSWORD=farm123
      - PORT=3033
      - ENV=development
      - PREFIX=farm
      - PLATFORM_URL=http://localhost:3033
    depends_on:
      mongodb:
        condition: service_healthy
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy
