services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=farm_db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  farm-bun:
    build:
      context: ../..
      dockerfile: examples/farm-bun/Dockerfile
    ports:
      - "3033:3033"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/farm_bun
      - PORT=3033
      - ENV=development
      - PREFIX=farm
      - PLATFORM_URL=http://localhost:3033
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3033/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
